trigger:
- main

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      displayName: 'terraform init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendAzureRmUseEntraIdForAuthentication: false
        backendServiceArm: 'Azure subscription 1(defaf26e-a23b-4a38-b4d4-dc9c52fb4b6d)'
        backendAzureRmResourceGroupName: 'newterrarg'
        backendAzureRmStorageAccountName: 'newterrastorage'
        backendAzureRmContainerName: 'tf-fetchresource'
        backendAzureRmKey: 'terraform.tfstate'
    
    - task: TerraformTask@5
      displayName: 'Terraform Format'
      inputs:
        provider: 'azurerm'
        command: 'validate'

    - task: TerraformTask@5
      displayName: 'Terraform Format'
      inputs:
        provider: 'azurerm'
        command: 'custom'
        outputTo: 'console'
        customCommand: 'fmt'
        environmentServiceNameAzureRM: 'Azure subscription 1(defaf26e-a23b-4a38-b4d4-dc9c52fb4b6d)'

    - task: TerraformTask@5
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'Azure subscription 1(defaf26e-a23b-4a38-b4d4-dc9c52fb4b6d)'
    
    
    - task: TerraformTask@5
      displayName: 'Terraform Apply'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        environmentServiceNameAzureRM: 'Azure subscription 1(defaf26e-a23b-4a38-b4d4-dc9c52fb4b6d)'
    
    - task: ArchiveFiles@2
      displayName: 'Archive File'
      inputs:
        rootFolderOrFile: '$(Build.BinariesDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true
    

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

